name: Discord Logo Push Notification

on:
  push:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed image files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif

      - name: Send to Discord
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          IMAGE_PATH="${{ steps.changed-files.outputs.all_changed_files }}"
          IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${IMAGE_PATH}"
          IMAGE_URL=$(echo "$IMAGE_URL" | sed 's/ /%20/g')

          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_MSG=$(echo "$COMMIT_MSG" | sed 's/"/\\"/g')
          COMMIT_URL="${{ github.event.head_commit.url }}"

          # Send with image URL in description instead of image field
          curl -H "Content-Type: application/json" \
            -d "{\"embeds\":[{\"title\":\"${COMMIT_MSG}\",\"url\":\"${IMAGE_URL}\",\"description\":\"[View Commit](${COMMIT_URL})\\n\\n${IMAGE_URL}\",\"color\":5814783,\"footer\":{\"text\":\"${{ github.repository }}\"}}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
