name: Discord Logo Push Notification

on:
  push:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed image files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif

      - name: Send to Discord
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Get first image file (preserving spaces)
          IMAGE_PATH="${{ steps.changed-files.outputs.all_changed_files }}"

          echo "Sending image: $IMAGE_PATH"

          # Build URL and encode ONLY spaces (not the protocol)
          IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${IMAGE_PATH}"
          IMAGE_URL=$(echo "$IMAGE_URL" | sed 's/ /%20/g')

          echo "Image URL: $IMAGE_URL"

          # Send to Discord
          curl -H "Content-Type: application/json" \
            -d "{\"embeds\":[{\"color\":5814783,\"image\":{\"url\":\"$IMAGE_URL\"},\"footer\":{\"text\":\"${{ github.repository }}\"}}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
