name: Discord Logo Push Notification

on:
  push:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed image files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif

      - name: Debug output
        run: |
          echo "Any changed: ${{ steps.changed-files.outputs.any_changed }}"
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Send to Discord
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Get first image file
          IMAGE_PATH=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | awk '{print $1}')
          echo "Sending image: $IMAGE_PATH"

          # Build URL with proper encoding
          IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${IMAGE_PATH}"
          IMAGE_URL=$(echo "$IMAGE_URL" | sed 's/ /%20/g; s/:/%3A/g')

          echo "Image URL: $IMAGE_URL"

          # Send to Discord with verbose output
          curl -v -H "Content-Type: application/json" \
            -d "{\"embeds\":[{\"color\":5814783,\"image\":{\"url\":\"$IMAGE_URL\"},\"footer\":{\"text\":\"${{ github.repository }}\"}}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
